"""Draft transformation-group bundles between two MDR data models (schema-exchange demo).

Pure functions, stdlib only. Given two MDR OpenAPI exports (``GET /datamodels/open_api_schema/{id}``
with ``include_attr_md``/``include_entity_md``/``full_export`` on) this brick proposes one JSONata
transformation per target attribute it can match, using two match sources:

1. **identity** — the attribute's full dotted name path (``Person.Contact.Email.emailAddress``) exists in
   both models. Both models usually derive from base LIF, so most attributes match this way.
2. **crosswalk** — an optional EDUcore-derived JSON of property and value equivalences anchored on CEDS.
3. **authored** — optional rules from an exported MDR transformation group (LIF-authored), re-pointed at
   the two models by ``UniqueName``; EDUcore value lookups are folded into them where they apply.

Every emitted rule carries its provenance in ``Alignment``: ``identity``,
``educore:<matchType>:<confidence>:<cedsKey>``, or ``<authored_label>`` (``+educore-values`` appended when a
lookup was folded in).

Expressions and ``EntityIdPath`` strings follow the style of ``reference_data/transformations/*.json`` and
the MDR mapping editor (``MappingsView.tsx``): the target root entity iterates the source root entity
(``{ "Person": Student. { ... } }``), array-valued nested entities are wrapped ``[{ ... }]``, and each
``EntityIdPath`` segment is ``{DataModelId}:{UniqueName}`` with ``~`` marking the attribute segment
(numeric prefixes are ignored on import; resolution is by ``UniqueName``).
"""

import hashlib
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone

BUNDLE_KIND = "transformation-group"
BUNDLE_FORMAT_VERSION = "1"
DRAFT_DESCRIPTION = "Draft generated by crosswalk_draft — review required"
_TITLE_PREFIX = "Machine-Readable Schema for "


@dataclass(frozen=True)
class AttributeRef:
    """One leaf attribute of a data model, addressed both by dotted name path and by portable EntityIdPath."""

    path: str
    """Dotted entity/attribute *Name* chain from the root entity, e.g. ``Person.Contact.Email.emailAddress``."""
    entity_id_path: str
    """Portable MDR path, e.g. ``1:Person,1:Common.Contact,1:Common.Contact.Email,1:~Common.Contact.Email.emailAddress``."""
    entity_arrays: tuple[bool, ...]
    """Per entity level (root first): whether the entity is array-valued (``"Array": "Yes"``)."""
    enum: tuple[str, ...] = ()
    """Value-set values when the attribute carries an ``enum``; empty otherwise."""

    @property
    def name(self) -> str:
        return self.path.rsplit(".", 1)[-1]


# ---------------------------------------------------------------------------
# Input shapes
# ---------------------------------------------------------------------------


def unwrap_openapi(document: dict) -> dict:
    """Accept either a bare OpenAPI dict or a data-model bundle whose ``dataModel.openapi`` holds it."""
    data_model = document.get("dataModel")
    if isinstance(data_model, dict) and isinstance(data_model.get("openapi"), dict):
        return data_model["openapi"]
    return document


def data_model_block(document: dict) -> dict:
    """Build the ``sourceDataModel``/``targetDataModel`` block: name/version/type/description + the OpenAPI."""
    openapi = unwrap_openapi(document)
    info = openapi.get("info", {})
    title = str(info.get("title", ""))
    name = title[len(_TITLE_PREFIX) :] if title.startswith(_TITLE_PREFIX) else title
    block = {
        "name": name,
        "version": info.get("version"),
        "type": None,
        "description": info.get("description"),
        "openapi": openapi,
    }
    data_model = document.get("dataModel")
    if isinstance(data_model, dict):
        for key in ("name", "version", "type", "description"):
            if data_model.get(key) is not None:
                block[key] = data_model[key]
    return block


# ---------------------------------------------------------------------------
# Attribute extraction
# ---------------------------------------------------------------------------


def _is_array(node: dict) -> bool:
    return node.get("Array") == "Yes" or node.get("type") == "array"


def _segment(node: dict, fallback_unique_name: str, attribute: bool = False) -> str:
    unique_name = node.get("UniqueName") or fallback_unique_name
    return f"{node.get('DataModelId', 0)}:{'~' if attribute else ''}{unique_name}"


def extract_attributes(openapi: dict) -> dict[str, AttributeRef]:
    """Walk an MDR OpenAPI export and return every leaf attribute keyed by dotted name path.

    A property whose value carries ``properties`` is a nested entity; anything else is an attribute.
    Inlined ``Reference``-placement copies (``RefCourse`` whose ``Name`` metadata is still ``Course``)
    are skipped so the referenced entity is only mapped once, at its real location.
    """
    attributes: dict[str, AttributeRef] = {}

    def walk(node: dict, names: list[str], segments: list[str], arrays: list[bool], entity_unique: str) -> None:
        for prop_name, prop in (node.get("properties") or {}).items():
            if not isinstance(prop, dict):
                continue
            if "properties" in prop:
                if prop.get("Name") and prop["Name"] != prop_name:
                    continue  # inlined Reference copy of another entity
                child_unique = prop.get("UniqueName") or f"{entity_unique}.{prop_name}"
                walk(
                    prop,
                    [*names, prop_name],
                    [*segments, _segment(prop, child_unique)],
                    [*arrays, _is_array(prop)],
                    child_unique,
                )
                continue
            path = ".".join([*names, prop_name])
            attributes[path] = AttributeRef(
                path=path,
                entity_id_path=",".join([*segments, _segment(prop, f"{entity_unique}.{prop_name}", attribute=True)]),
                entity_arrays=tuple(arrays),
                enum=tuple(str(value) for value in prop.get("enum") or ()),
            )

    for root_name, root in (openapi.get("components", {}).get("schemas") or {}).items():
        if isinstance(root, dict):
            root_unique = root.get("UniqueName") or root_name
            walk(root, [root_name], [_segment(root, root_unique)], [_is_array(root)], root_unique)
    return attributes


def resolve_path(path: str, attributes: dict[str, AttributeRef]) -> AttributeRef | None:
    """Find an attribute by full dotted path, falling back to the trailing ``Entity.attribute`` pair.

    When several attributes share the trailing pair, the first in path order is chosen (deterministic;
    the draft is reviewed by a human anyway).
    """
    if path in attributes:
        return attributes[path]
    tail = ".".join(path.split(".")[-2:])
    for candidate_path in sorted(attributes):
        if candidate_path == tail or candidate_path.endswith("." + tail):
            return attributes[candidate_path]
    return None


def _stem(name: str) -> str:
    """Case-fold and drop a trailing ``Descriptor`` (Ed-Fi's option-set naming) for tolerant matching."""
    lowered = name.lower()
    return lowered[: -len("descriptor")] if lowered.endswith("descriptor") else lowered


def resolve_source_path(path: str, attributes: dict[str, AttributeRef]) -> AttributeRef | None:
    """``resolve_path`` plus Ed-Fi descriptor tolerance.

    ``Address.StateAbbreviationDescriptor`` finds ``Address.StateAbbreviation``; a stem with no exact
    attribute falls back to the single attribute whose name contains it (``GradeLevel`` ->
    ``OfferedGradeLevel``). Ambiguous stems resolve to nothing — the draft is reviewed by a human.
    """
    found = resolve_path(path, attributes)
    if found is not None:
        return found
    stem = _stem(path.rsplit(".", 1)[-1])
    exact = [ref for ref in attributes.values() if _stem(ref.name) == stem]
    if len(exact) == 1:
        return exact[0]
    partial = [ref for ref in attributes.values() if stem in _stem(ref.name)]
    return partial[0] if len(partial) == 1 else None


def _unique_name(entity_id_path: str | None) -> str | None:
    """``'6:Course,6:~Course.CourseTitle'`` -> ``'Course.CourseTitle'`` (portable part of the last segment)."""
    if not entity_id_path:
        return None
    return entity_id_path.rsplit(",", 1)[-1].split(":", 1)[-1].lstrip("~")


def _by_unique_name(attributes: dict[str, AttributeRef]) -> dict[str, AttributeRef]:
    return {_unique_name(ref.entity_id_path) or ref.path: ref for ref in attributes.values()}


# ---------------------------------------------------------------------------
# Expression building
# ---------------------------------------------------------------------------


def build_lookup_term(value_map: dict[str, str], source_term: str) -> str:
    """Wrap ``source_term`` in ``$lookup({...}, term)`` so unmapped values pass through as null."""
    mapping = json.dumps(dict(sorted(value_map.items())), ensure_ascii=False)
    return f"$lookup({mapping}, {source_term})"


def build_expression(target: AttributeRef, source: AttributeRef, value_map: dict[str, str] | None = None) -> str:
    """Build the default JSONata for ``source -> target`` in the MappingsView / reference-file style.

    ``{ "Person": Course. { "CourseLearningExperience": [{ "Course": [{ "name": CourseTitle }] }] } }``
    """
    source_segments = source.path.split(".")
    source_term = ".".join(source_segments[1:]) or "$"
    if value_map:
        source_term = build_lookup_term(value_map, source_term)

    target_segments = target.path.split(".")
    inner = f'"{target_segments[-1]}": {source_term}'
    for level in range(len(target_segments) - 2, 0, -1):
        wrapped = f"[{{ {inner} }}]" if target.entity_arrays[level] else f"{{ {inner} }}"
        inner = f'"{target_segments[level]}": {wrapped}'
    return f'{{ "{target_segments[0]}": {source_segments[0]}. {{ {inner} }} }}'


# ---------------------------------------------------------------------------
# Bundle assembly
# ---------------------------------------------------------------------------


def apply_value_map_to_expression(expression: str, source_name: str, value_map: dict[str, str]) -> str | None:
    """Fold a value lookup into an authored expression when the bare source term appears exactly once.

    Returns the rewritten expression, or ``None`` when the rewrite would be ambiguous (term absent or
    repeated, or a ``$lookup`` already present) — the caller then keeps the expression untouched.
    """
    if "$lookup(" in expression:
        return None
    pattern = re.compile(r'(?<![\w."])' + re.escape(source_name) + r'(?![\w"])')
    if len(pattern.findall(expression)) != 1:
        return None
    return pattern.sub(lambda _match: build_lookup_term(value_map, source_name), expression, count=1)


def compute_checksum(payload: dict) -> str:
    """``sha256:<hex>`` over canonical JSON of the bundle without its ``manifest`` key."""
    body = {key: value for key, value in payload.items() if key != "manifest"}
    canonical = json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    return "sha256:" + hashlib.sha256(canonical).hexdigest()


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _transformation(target: AttributeRef, source: AttributeRef, alignment: str, notes: str, value_map: dict) -> dict:
    return {
        "Name": target.path,
        "Expression": build_expression(target, source, value_map or None),
        "ExpressionLanguage": "JSONata",
        "Alignment": alignment,
        "Notes": notes,
        "SourceAttributes": [{"EntityIdPath": source.entity_id_path}],
        "TargetAttribute": {"EntityIdPath": target.entity_id_path},
    }


def _value_map_for(
    source: AttributeRef, target: AttributeRef, value_groups: dict[tuple[str, str], dict[str, str]]
) -> dict[str, str]:
    """Collect crosswalk value equivalences that apply to this (source, target) pair."""
    applied: dict[str, str] = {}
    for (source_option_set, target_option_set), value_map in value_groups.items():
        target_hit = target_option_set in (target.path, ".".join(target.path.split(".")[-2:]))
        # Descriptor-stem tolerance (``SexDescriptor`` ~ ``Sex`` ~ ``OfferedGradeLevel``) applies only to
        # enum-less sources: MDR's Ed-Fi model types descriptors as plain strings, while a LIF source
        # carries LIF values that an Ed-Fi-keyed lookup would null out.
        tolerant_hit = not source.enum and (
            _stem(source.name) == _stem(source_option_set) or _stem(source_option_set) in _stem(source.name)
        )
        source_hit = (
            source.name == source_option_set
            or tolerant_hit
            or (bool(source.enum) and set(source.enum) == set(value_map))
        )
        # A crosswalk row asserts (sourceOptionSet -> targetOptionSet); it only applies when BOTH sides
        # match. A target-only hit would wrap, e.g., a LIF->LIF addressState copy in an Ed-Fi lookup and
        # null out every real LIF value.
        if target_hit and source_hit:
            applied.update(value_map)
    return applied


def generate_draft_bundle(
    source_openapi: dict,
    target_openapi: dict,
    *,
    group_name: str,
    group_version: str = "0.1",
    publisher: str = "crosswalk_draft",
    crosswalk: dict | None = None,
    min_confidence: float = 0.5,
    authored: list[dict] | None = None,
    authored_label: str = "lif-authored",
    rule_notes: dict[str, str | dict] | None = None,
) -> tuple[dict, dict]:
    """Generate a Draft transformation-group bundle and a match report.

    Returns ``(bundle, report)``. The bundle is the portable shape consumed by the schema-exchange
    ``/exchange/receive`` endpoint; the report lists identity/crosswalk/authored counts, applied value
    lookups, unmatched attributes on both sides, crosswalk rows dropped for low confidence, and authored
    rules that could not be re-pointed. ``authored`` takes the ``Transformations`` list of an exported MDR
    group; each rule keeps its expression and is resolved to the two models by ``UniqueName``.
    ``rule_notes`` is an optional overlay keyed by target path (the rule ``Name``): a string is the rule's
    ``Notes``; a dict may carry ``Notes``, ``SourceAttributeNotes`` (keyed by source ``UniqueName``) and
    ``TargetAttributeNotes``. Authored rules take the note as-is, generated rows keep their provenance text
    and get it appended; keys that match no rule are reported under ``notesUnmatched``.
    """
    crosswalk = crosswalk or {}
    source_attributes = extract_attributes(unwrap_openapi(source_openapi))
    target_attributes = extract_attributes(unwrap_openapi(target_openapi))

    below_confidence: list[dict] = []

    # Value equivalences, grouped by (sourceOptionSet, targetOptionSet).
    value_groups: dict[tuple[str, str], dict[str, str]] = {}
    for row in crosswalk.get("values") or []:
        confidence = float(row.get("confidence", 1.0))
        if confidence < min_confidence:
            below_confidence.append(
                {
                    "sourcePath": f"{row.get('sourceOptionSet')}={row.get('sourceValue')}",
                    "targetPath": f"{row.get('targetOptionSet')}={row.get('targetValue')}",
                    "confidence": confidence,
                }
            )
            continue
        key = (str(row.get("sourceOptionSet")), str(row.get("targetOptionSet")))
        value_groups.setdefault(key, {})[str(row.get("sourceValue"))] = str(row.get("targetValue"))

    matches: dict[str, tuple[AttributeRef, str, str]] = {}  # target path -> (source, alignment, notes)

    # 1. identity
    for path, target in target_attributes.items():
        if path in source_attributes:
            matches[path] = (source_attributes[path], "identity", "identity: same path in both models")
    identity_count = len(matches)

    # 2. crosswalk properties (highest confidence first; identity and earlier rows win)
    property_rows = sorted(crosswalk.get("properties") or [], key=lambda row: -float(row.get("confidence", 0.0)))
    crosswalk_count = 0
    for row in property_rows:
        confidence = float(row.get("confidence", 0.0))
        source_path, target_path = str(row.get("sourcePath")), str(row.get("targetPath"))
        if confidence < min_confidence:
            below_confidence.append({"sourcePath": source_path, "targetPath": target_path, "confidence": confidence})
            continue
        source = resolve_source_path(source_path, source_attributes)
        target = resolve_path(target_path, target_attributes)
        if source is None or target is None or target.path in matches:
            continue
        match_type, ceds_key = row.get("matchType", ""), row.get("cedsKey", "")
        alignment = f"educore:{match_type}:{confidence}:{ceds_key}"
        notes = f"EDUcore crosswalk: CEDS {ceds_key} {row.get('cedsName', '')} ({match_type}, {confidence})".strip()
        matches[target.path] = (source, alignment, notes)
        crosswalk_count += 1

    # 3. authored rules (re-pointed by UniqueName; generated rows above win for the same target)
    authored_rules: dict[str, tuple[list[AttributeRef], dict]] = {}  # target path -> (sources, rule)
    authored_skipped: list[dict] = []
    if authored:
        source_by_unique = _by_unique_name(source_attributes)
        target_by_unique = _by_unique_name(target_attributes)
        for rule in authored:
            target_unique = _unique_name((rule.get("TargetAttribute") or {}).get("EntityIdPath"))
            target = target_by_unique.get(target_unique or "")
            sources = [
                source_by_unique.get(_unique_name(attribute.get("EntityIdPath")) or "")
                for attribute in rule.get("SourceAttributes") or []
            ]
            if target is None or not sources or any(ref is None for ref in sources) or not rule.get("Expression"):
                authored_skipped.append({"name": rule.get("Name"), "reason": "unresolved path or empty expression"})
            elif target.path in matches or target.path in authored_rules:
                authored_skipped.append({"name": rule.get("Name"), "reason": f"target already mapped: {target.path}"})
            else:
                authored_rules[target.path] = ([ref for ref in sources if ref is not None], rule)
    authored_count = len(authored_rules)

    # 4. value lookups + transformation records
    transformations: list[dict] = []
    lookups_applied = 0
    for target_path in sorted(matches):
        source, alignment, notes = matches[target_path]
        target = target_attributes[target_path]
        value_map = _value_map_for(source, target, value_groups)
        if value_map:
            lookups_applied += 1
            notes = f"{notes}; value lookup: {len(value_map)} values"
        transformations.append(_transformation(target, source, alignment, notes, value_map))
    for target_path in sorted(authored_rules):
        sources, rule = authored_rules[target_path]
        target = target_attributes[target_path]
        expression, alignment = str(rule["Expression"]), authored_label
        # An authored rule's own Notes (the mapping rationale / caveat) travel with it; the seeded marker is the fallback.
        notes = rule.get("Notes") or f"seeded from authored rule '{rule.get('Name')}'"
        value_map = _value_map_for(sources[0], target, value_groups) if len(sources) == 1 else {}
        if value_map:
            rewritten = apply_value_map_to_expression(expression, sources[0].name, value_map)
            if rewritten is not None:
                expression, alignment = rewritten, f"{authored_label}+educore-values"
                lookups_applied += 1
                notes = f"{notes}; value lookup: {len(value_map)} values"
        transformations.append(
            {
                "Name": target.path,
                "Expression": expression,
                "ExpressionLanguage": "JSONata",
                "Alignment": alignment,
                "Notes": notes,
                "SourceAttributes": [{"EntityIdPath": ref.entity_id_path} for ref in sources],
                "TargetAttribute": {"EntityIdPath": target.entity_id_path},
            }
        )

    # 5. notes overlay (human rationale / caveats, keyed by target path)
    pending_notes = dict(rule_notes or {})
    notes_applied = 0
    for record in transformations:
        entry = pending_notes.pop(record["Name"], None)
        if entry is None:
            continue
        entry = {"Notes": entry} if isinstance(entry, str) else entry
        if entry.get("Notes"):
            if record["Alignment"].startswith(authored_label):
                record["Notes"] = entry["Notes"]
            else:  # generated rows keep the machine provenance and gain the human note
                record["Notes"] = f"{record['Notes']}; {entry['Notes']}"
        source_notes = entry.get("SourceAttributeNotes") or {}
        for attribute in record["SourceAttributes"]:
            note = source_notes.get(_unique_name(attribute["EntityIdPath"]) or "")
            if note:
                attribute["Notes"] = note
        if entry.get("TargetAttributeNotes"):
            record["TargetAttribute"]["Notes"] = entry["TargetAttributeNotes"]
        notes_applied += 1

    matched_sources = {source.path for source, _, _ in matches.values()}
    matched_sources.update(ref.path for sources, _ in authored_rules.values() for ref in sources)
    mapped_targets = set(matches) | set(authored_rules)
    report = {
        "identityMatches": identity_count,
        "crosswalkMatches": crosswalk_count,
        "authoredMatches": authored_count,
        "valueLookupsApplied": lookups_applied,
        "unmatchedSource": sorted(set(source_attributes) - matched_sources),
        "unmatchedTarget": sorted(set(target_attributes) - mapped_targets),
        "belowConfidence": below_confidence,
        "authoredSkipped": authored_skipped,
        "notesApplied": notes_applied,
        "notesUnmatched": sorted(pending_notes),
    }

    payload = {
        "sourceDataModel": data_model_block(source_openapi),
        "targetDataModel": data_model_block(target_openapi),
        "transformationGroup": {
            "Name": group_name,
            "GroupVersion": group_version,
            "Description": DRAFT_DESCRIPTION,
            "Notes": (
                f"identity={identity_count}; crosswalk={crosswalk_count}; authored={authored_count}; "
                f"valueLookups={lookups_applied}; "
                f"unmatchedSource={len(report['unmatchedSource'])}; unmatchedTarget={len(report['unmatchedTarget'])}; "
                f"belowConfidence={len(below_confidence)}"
            ),
            "Transformations": transformations,
        },
    }
    manifest = {
        "kind": BUNDLE_KIND,
        "formatVersion": BUNDLE_FORMAT_VERSION,
        "publisher": publisher,
        "exportedAt": _utc_now(),
        "name": group_name,
        "version": group_version,
        "checksum": compute_checksum(payload),
    }
    return {"manifest": manifest, **payload}, report
